server:
    host: 0.0.0.0
    port: 8080
    context-path: '/ca-ct'
logging:
    level:
        console: DEBUG
        file: INFO
    filename: 'logs/cloud_telephony_logs.log'
    format: '%(asctime)s > %(levelname)s [%(name)s] --- %(message)s'
    max_file_size: 10485760  # 10 MB
    backup_count: 5

app:
    application-name: Cloud Telephony Services
    profiles:
        active: dev
    datasource:
        dev:
            database1-db:
                conn_string: "${DATABASE1_URL}"
                driver-name: "${DB1_DRIVER_NAME}"
                host: "${DB1_HOST}"
                port: "${DB1_PORT}"
                username: "${DB1_USER}"
                database-name: "${DB1_NAME}"
                password: "${DB1_PASSWORD}"
        staging:
            database1-db:
                conn_string: "postgresql://postgres:postgres123@localhost:5432/cloudtelephony"
                driver-name: postgresql
                host: localhost
                port: 5432
                username: postgres
                database-name: cloudtelephony
                password: postgres123
